const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveBuckets: (buckets) => ipcRenderer.invoke('save-buckets', buckets),
  setLeague: (league) => ipcRenderer.invoke('set-league', league),
  setDefaults: (items, enabled) => ipcRenderer.invoke('set-defaults', items, enabled),
  setOverrides: (overrides) => ipcRenderer.invoke('set-overrides', overrides),
  setTutorialDone: () => ipcRenderer.invoke('set-tutorial-done'),
  setTutorialDismissed: () => ipcRenderer.invoke('set-tutorial-dismissed'),
  getFeedStatus: () => ipcRenderer.invoke('get-feed-status'),
  onFeedChanged: (cb) => ipcRenderer.on('feed-changed', cb),
  getUpdateState: () => ipcRenderer.invoke('get-update-state'),
  onUpdateState: (cb) => ipcRenderer.on('update-state', (_e, s) => cb(s)),
  onLeagueAutoChanged: (cb) => ipcRenderer.on('league-auto-changed', (_e, s) => cb(s)),
  installUpdate: () => ipcRenderer.send('install-update'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  isDevBuild: () => ipcRenderer.invoke('is-dev-build'),
  setUiScale: (v) => ipcRenderer.invoke('set-ui-scale', v),
  setBgOpacity: (v) => ipcRenderer.invoke('set-bg-opacity', v),
  setExcludeExaltedArb: (on) => ipcRenderer.invoke('set-exclude-exalted-arb', on),
  setCurrencyIcons: (on) => ipcRenderer.invoke('set-currency-icons', on),
  checkUpdates: () => ipcRenderer.send('check-updates-now'),
  getLiveRates: () => ipcRenderer.invoke('get-live-rates'),
  onLiveRates: (cb) => ipcRenderer.on('live-rates', (_e, r) => cb(r)),
  setHotkey: (accelerator) => ipcRenderer.invoke('set-hotkey', accelerator),
  setItemHotkeys: (binds) => ipcRenderer.invoke('set-item-hotkeys', binds),
  onTempMode: (cb) => ipcRenderer.on('overlay-temp-mode', (_e, v) => cb(v)),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  submitFeedback: (payload) => ipcRenderer.invoke('submit-feedback', payload),
  fetchPrices: (force) => ipcRenderer.invoke('fetch-prices', force),
  fetchCatalog: () => ipcRenderer.invoke('fetch-catalog'),
  getCxCatalog: () => ipcRenderer.invoke('get-cx-catalog'),
  directBarter: (args) => ipcRenderer.invoke('direct-barter', args),
  setBarterMode: (mode) => ipcRenderer.invoke('set-barter-mode', mode),
  cxItemPrice: (args) => ipcRenderer.invoke('cx-item-price', args),
  listLeagues: () => ipcRenderer.invoke('list-leagues'),
  leagueNames: () => ipcRenderer.invoke('league-names'),
  hide: (toGame) => ipcRenderer.send('hide-overlay', !!toGame),
  focusOverlay: () => ipcRenderer.send('focus-overlay'),
  quit: () => ipcRenderer.send('quit-app'),
  onShown: (cb) => ipcRenderer.on('overlay-shown', cb),
  // item price-check (trade2)
  trade2Search: (league, query) => ipcRenderer.invoke('trade2-search', { league, query }),
  trade2Fetch: (ids, queryId) => ipcRenderer.invoke('trade2-fetch', { ids, queryId }),
  trade2SearchFetch: (league, query, limit) => ipcRenderer.invoke('trade2-search-fetch', { league, query, limit }),
  trade2Leagues: () => ipcRenderer.invoke('trade2-leagues'),
  trade2AuthCheck: (league, force) => ipcRenderer.invoke('trade2-auth-check', { league, force }),
  setActiveTab: (which) => ipcRenderer.send('active-tab', which),
  stashCaptureStart: () => ipcRenderer.send('stash-capture-start'),
  setStashDupTabs: (on) => ipcRenderer.invoke('set-stash-dup', on),
  setStashBannerHidden: (on) => ipcRenderer.invoke('set-stash-banner-hidden', on),
  setStashSortLayout: (on) => ipcRenderer.invoke('set-stash-sort', on),
  setStashShowMissing: (on) => ipcRenderer.invoke('set-stash-show-missing', on),
  setStashShowConfidence: (on) => ipcRenderer.invoke('set-stash-show-confidence', on),
  setStashHotkey: (accelerator) => ipcRenderer.invoke('set-stash-hotkey', accelerator),
  setRepriceHotkey: (accelerator) => ipcRenderer.invoke('set-reprice-hotkey', accelerator),
  setRepriceConfig: (cfg) => ipcRenderer.invoke('set-reprice-config', cfg),
  // the reprice box uses the SAME calibration window as Net Worth - one flow, one
  // confirm button. It reports back by event, not by resolving a promise.
  repriceCalibrate: () => ipcRenderer.send('stash-calibrate-start', { target: 'reprice' }),
  // second box, over the currency icon beside the number - optional, and only needed by
  // rules that treat currencies differently
  repriceIconCalibrate: () => ipcRenderer.send('stash-calibrate-start', { target: 'reprice-icon' }),
  onRepriceCalibrated: (fn) => ipcRenderer.on('reprice-calibrated', (_e, p) => fn(p)),
  repriceTestRead: () => ipcRenderer.invoke('reprice-test-read'),
  repriceTestIcon: () => ipcRenderer.invoke('reprice-test-icon'),
  // the currencies the icon matcher can actually name, for the "if the currency is..."
  // picker - offering one it cannot detect would be a rule that never fires
  repriceCurrencies: () => ipcRenderer.invoke('reprice-currencies'),
  // crops taken at a screen size we have no digit templates for, offered for submission
  // so the corpus can cover it - see REPRICE-SAMPLES in main
  repriceShotCapture: (slot) => ipcRenderer.invoke('reprice-shot-capture', slot),
  repriceShotDrop: (slot) => ipcRenderer.invoke('reprice-shot-drop', slot),
  repriceShotPreview: (slot) => ipcRenderer.invoke('reprice-shot-preview', slot),
  repriceShotSend: (payload) => ipcRenderer.invoke('reprice-shot-send', payload),
  repriceSamples: () => ipcRenderer.invoke('reprice-samples'),
  repriceSamplesSend: (payload) => ipcRenderer.invoke('reprice-samples-send', payload),
  repriceSamplesClear: () => ipcRenderer.invoke('reprice-samples-clear'),
  onRepriceSampleReady: (fn) => ipcRenderer.on('reprice-sample-ready', (_e, p) => fn(p)),
  onRepriceMode: (fn) => ipcRenderer.on('reprice-mode', (_e, on) => fn(!!on)),
  stashSampleCapture: () => ipcRenderer.invoke('stash-sample-capture'),
  stashSampleDrop: (i) => ipcRenderer.invoke('stash-sample-drop', i),
  stashSampleScope: (i, scope) => ipcRenderer.invoke('stash-sample-scope', i, scope),
  stashSamplePreview: (i) => ipcRenderer.invoke('stash-sample-preview', i),
  stashSampleReset: () => ipcRenderer.invoke('stash-sample-reset'),
  stashSampleSend: (payload) => ipcRenderer.invoke('stash-sample-send', payload),
  resizeWindowBy: (dx, dy) => ipcRenderer.send('resize-window-by', { dx, dy }),
  stashCalibrateStart: () => ipcRenderer.send('stash-calibrate-start'),
  clearStashCalibration: () => ipcRenderer.invoke('clear-stash-calibration'),
  onStashCalibrated: (cb) => ipcRenderer.on('stash-calibrated', (_e, res) => cb(res)),
  onStashCapturing: (cb) => ipcRenderer.on('stash-capturing', () => cb()),
  onStashDetected: (cb) => ipcRenderer.on('stash-detected', (_e, tab) => cb(tab)),
  onStashCaptured: (cb) => ipcRenderer.on('stash-captured', (_e, res) => cb(res)),
  onStashQueued: (cb) => ipcRenderer.on('stash-queued', (_e, info) => cb(info)),
  setCurrencyRates: (rates) => ipcRenderer.invoke('set-currency-rates', rates),
  setTheme: (name) => ipcRenderer.invoke('set-theme', name),
  setDyslexicFont: (on) => ipcRenderer.invoke('set-dyslexic-font', on),
  setSeenVersion: (version) => ipcRenderer.invoke('set-seen-version', version),
  poeLogin: () => ipcRenderer.invoke('poe-login'),
  setItemHistory: (history) => ipcRenderer.invoke('set-item-history', history),
  setDesecHistory: (history) => ipcRenderer.invoke('set-desec-history', history),
  setRegexBuckets: (buckets) => ipcRenderer.invoke('set-regex-buckets', buckets),
  setTabShown: (which, shown) => ipcRenderer.invoke('set-tab-shown', which, shown),
  setTabOrder: (order) => ipcRenderer.invoke('set-tab-order', order),
  getSafeCommands: () => ipcRenderer.invoke('get-safe-commands'),
  setLanguage: (code) => ipcRenderer.invoke('set-language', code),
  // synchronous ON PURPOSE: i18n.js reads this at load, before anything renders
  uiLang: (() => { try { return ipcRenderer.sendSync('get-ui-lang'); } catch { return 'en'; } })(),
  debug: !!process.env.POE2_OVERLAY_DEBUG, // gates the QA pseudo-locale in the language list
  platform: process.platform, // renderer copy is read-only; used for platform caveats in Settings
  // Net Worth frames on platforms where main can't capture (see renderer/stash/linux-capture.js)
  onStashNeedFrame: (cb) => ipcRenderer.on('stash-need-frame', (_e, opts) => cb(opts)),
  sendStashFrame: (payload) => ipcRenderer.send('stash-frame', payload),
  setGrandexHistory: (history) => ipcRenderer.invoke('set-grandex-history', history),
  setCommandHotkeys: (rows) => ipcRenderer.invoke('set-command-hotkeys', rows),
  setItemRanges: (ranges) => ipcRenderer.invoke('set-item-ranges', ranges),
  setGarbagePool: (ids) => ipcRenderer.invoke('set-garbage-pool', ids),
  setItemSearchOpts: (o) => ipcRenderer.invoke('set-item-search-opts', o),
  itemPeekShow: (payload) => ipcRenderer.send('item-peek-show', payload),
  itemPeekHide: () => ipcRenderer.send('item-peek-hide'),
  readClipboard: () => ipcRenderer.invoke('read-clipboard'),
  onItemCopied: (cb) => ipcRenderer.on('item-copied', (_e, text) => cb(text)),
  onBarterFocusSearch: (cb) => ipcRenderer.on('barter-focus-search', cb),
  onItemCopyFailed: (cb) => ipcRenderer.on('item-copy-failed', () => cb()),
  onTrade2Wait: (cb) => ipcRenderer.on('trade2-wait', (_e, info) => cb(info)),
  writeClipboard: (text) => ipcRenderer.invoke('write-clipboard', text)
});
